fill_infoBasic <- function(){

  library(readtext)
  library(ragtop)
  library(dplyr)
  library(magicfor)
  library(stringr)

  # List of Species file (fill_profiles_in_oldSystem.csv) ####

  ## Get local path of the downloaded list of species file ####

  listOfSpecies_localPath <- paste0(

    sub("Packages/CNCFloraR", "", getwd()),
    "/CNCFlora_data/inputs/listOfSpecies_for_processing/fill_profiles_in_oldSystem.csv"

  )

  ## Ask to open the list of species file ####

  answer <- ""

  while(answer != "Y" |
        answer != "N" ){

    answer <-
      toupper(readline("Open the list of species file? (y/n): "))

    if(answer == "Y"){

      shell(listOfSpecies_localPath)

      answer2 <- ""

      while(answer2 != "Y"){

        answer2 <-
          toupper(readline("List of species file ready? (y): "))

        if(answer2 == "Y"){

          break

        }

      }

      break

    }

    if(answer == "N"){

      break

    }

  }

  ## Import the list of species file from local path ####

  listOfSpecies <- fread(

    listOfSpecies_localPath,
    header = F,
    sep = ";",
    encoding = "UTF-8"

  )

  profileIDs <- fread(

    paste0(

      sub("Packages/CNCFloraR", "", getwd()),
      "/CNCFlora_data/inputs/profileIDs_in_oldSystem/profileIDs.txt"

    ),
    header = F

  )

  profileIDs$V2 <- gsub("\\/edit","", profileIDs$V2)
  profileIDs$V2 <- gsub("http.*profile:","", profileIDs$V2)

  colnames(profileIDs) <- c("V2", "profileID")

  listOfSpecies <- left_join(listOfSpecies, profileIDs, by = "V2")

  colnames(listOfSpecies) <- c("recorte", "species", "flow", "profileID")


  infoBasicTable <- fread(

    paste0(

      sub("Packages/CNCFloraR", "", getwd()),
      "/CNCFlora_data/inputs/oldSystem_fill_tables/infobasic_table.csv"

    ),
    header = T,
    sep = ";",
    encoding = "UTF-8"

  )

  data <- infoBasicTable %>% filter(species %in% listOfSpecies$species)

  listOfSpecies_n <- 1:length(listOfSpecies$species)

  for(i in listOfSpecies_n){
    recorte <- listOfSpecies$recorte[i]
    Species <- listOfSpecies$species[i]
    profile_sp <- listOfSpecies$profileID[i]

    data_species <- data %>% dplyr::filter(species==Species)
    Especie_obra<-data_species %>% dplyr::filter(variable=="obra princeps")
    Especie_EOO<-data_species %>% dplyr::filter(variable=="EOO")
    Especie_AOO<-data_species %>% dplyr::filter(variable=="AOO")
    Especie_endemism<-data_species %>% dplyr::filter(variable=="FB2020_endemism")
    Especie_endemism$info<-sub("Sim", "2", Especie_endemism$info)
    Especie_endemism$info<-sub("Não", "3", Especie_endemism$info)
    Especie_DistGeo<-data_species %>% dplyr::filter(variable=="Distribuição geográfica")
    Especie_Ref_FB2020<-data_species %>% dplyr::filter(variable=="Ref_FB2020")
    Especie_lifeForm<-data_species %>% dplyr::filter(variable=="lifeForm")
    Especie_lifeForm$info<-sub("Erva", "3", Especie_lifeForm$info)
    Especie_lifeForm$info<-sub("Arbusto", "4", Especie_lifeForm$info)
    Especie_lifeForm$info<-sub("Á\u0081rvore", "5", Especie_lifeForm$info)
    Especie_lifeForm$info<-sub("Árvore", "5", Especie_lifeForm$info)
    Especie_lifeForm$info<-sub("Palmeira", "5", Especie_lifeForm$info)
    Especie_lifeForm$info<-sub("Liana/volúvel/trepadeira", "6", Especie_lifeForm$info)
    Especie_lifeForm$info<-sub("Subarbusto", "7", Especie_lifeForm$info)
    Especie_lifeForm$info<-sub("Arvoreta", "8", Especie_lifeForm$info)
    Especie_lifeForm$numero<-as.numeric(count(as.data.frame(strsplit(Especie_lifeForm$info,"-"))))
    Especie_lifeForm2<-data.frame(strsplit(Especie_lifeForm$info,"-"))
    Especie_lifeForm2<-as.data.frame(t(Especie_lifeForm2))
    row.names(Especie_lifeForm2)<-""
    Especie_lifeForm<-cbind(Especie_lifeForm,Especie_lifeForm2)
    Especie_habit<-data_species %>% dplyr::filter(variable=="habitat")
    Especie_habit$info<-sub("Terrícola", "3", Especie_habit$info)
    Especie_habit$info<-sub("Aquática", "4", Especie_habit$info)
    Especie_habit$info<-sub("Rupícola", "5", Especie_habit$info)
    Especie_habit$info<-sub("Hemiepífita", "8", Especie_habit$info)
    Especie_habit$numero<-as.numeric(count(as.data.frame(strsplit(Especie_habit$info,"-"))))
    Especie_habit2<-data.frame(strsplit(Especie_habit$info,"-"))
    Especie_habit2<-as.data.frame(t(Especie_habit2))
    row.names(Especie_habit2)<-""
    Especie_habit<-cbind(Especie_habit,Especie_habit2)
    Especie_bioma<-data_species %>% dplyr::filter(variable=="occurrenceRemarks")
    Especie_bioma$info<-sub("Amazônia", "1", Especie_bioma$info)
    Especie_bioma$info<-sub("Mata\\sAtlântica", "2", Especie_bioma$info)
    Especie_bioma$info<-sub("Caatinga", "3", Especie_bioma$info)
    Especie_bioma$info<-sub("Pampa\\s\\(Campos\\sSulinos\\)", "4", Especie_bioma$info)
    Especie_bioma$info<-sub("Pampa", "4", Especie_bioma$info)
    Especie_bioma$info<-sub("Cerrado", "5", Especie_bioma$info)
    Especie_bioma$info<-sub("Pantanal", "6", Especie_bioma$info)
    Especie_bioma$numero<-as.numeric(count(as.data.frame(strsplit(Especie_bioma$info,"-"))))
    Especie_bioma2<-data.frame(strsplit(Especie_bioma$info,"-"))
    Especie_bioma2<-as.data.frame(t(Especie_bioma2))
    row.names(Especie_bioma2)<-""
    Especie_bioma<-cbind(Especie_bioma,Especie_bioma2)
    Especie_veget<-data_species %>% dplyr::filter(variable=="vegetationType")
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s1\\.6\\(arbórea)\\/3\\.6\\(arbustiva\\)\\/4\\.6\\(herbácea\\)\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s1\\.5\\(predominantemente\\sarbóreo\\)\\/2\\.1\\(savana\\sseca\\)\\/2\\.2\\(savana\\súmida\\)\\/3\\.5\\(predominantemente\\sarbustivo\\)\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s1\\.5\\(predominantemente\\sarbórea\\)\\/3\\.5\\(predominantemente\\sarbustiva\\)\\/13\\.3\\(dunas\\)\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[3\\.7\\(arbustivo)\\/4\\.7\\(herbáceo\\)\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s2\\.1\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s14\\.1\\(áreas\\saráveis\\)\\/14\\.2\\(pastagens\\)\\/14\\.3\\(plantações\\sem\\slarga\\sescala,\\smonoculturas\\)\\/14\\.4\\(agricultura\\sfamiliar,\\sou\\sem\\spequena\\sescala\\)\\/14\\.5\\(urbana,\\scomercial,\\sindustrial\\)\\/14\\.6\\(vegetação\\ssecundária\\sou\\sdegradada\\)\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s3\\.7\\(arbustivo\\)\\/4\\.7\\(herbáceo\\)\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s1\\.5\\(seco\\)\\/1\\.6\\(úmido\\se\\sabaixo\\sde\\s1200\\sm\\salt\\.\\)\\/1\\.9\\(úmido\\se\\sacima\\sde\\s1200\\sm\\salt\\.\\)\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s3\\.5\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s1\\.6\\(até\\s1200\\sm\\salt\\.\\)\\/1\\.9\\(acima\\sde\\s1200\\sm\\salt\\.\\)\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s5\\.1\\/5\\.2\\/5\\.3\\/5\\.4\\/5\\.5\\/5\\.6\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s1\\.6\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s1\\.8\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s1\\.5\\/2\\.1\\(seco\\)\\/2\\.2\\(úmido\\)\\/3\\.5\\(predominantemente\\sarbustivo\\)\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s4\\.6\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s2\\.1\\(seco\\)\\/2\\.2\\(úmido\\)\\/4\\.4\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s2\\.1\\(seco\\)\\/2\\.2\\(úmido\\)\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s4\\.4\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s2\\.1\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s1\\.5\\]", "", Especie_veget$info)
    Especie_veget$info<-gsub("\\s\\[IUCN\\sHabitat:\\s6\\]", "", Especie_veget$info)
    Especie_veget$info<-sub("Área Antrópica", "1", Especie_veget$info)
    Especie_veget$info<-sub("Caatinga \\(stricto sensu\\)", "2", Especie_veget$info)
    Especie_veget$info<-sub("Campinarana", "3", Especie_veget$info)
    Especie_veget$info<-sub("Campo de Altitude", "4", Especie_veget$info)
    Especie_veget$info<-sub("Campo de Várzea", "5", Especie_veget$info)
    Especie_veget$info<-sub("Campo Limpo", "6", Especie_veget$info)
    Especie_veget$info<-sub("Campo rupestre", "7", Especie_veget$info)
    Especie_veget$info<-sub("Carrasco", "8", Especie_veget$info)
    Especie_veget$info<-sub("Cerrado \\(lato sensu\\)", "9", Especie_veget$info)
    Especie_veget$info<-sub("Floresta Ciliar ou Galeria", "10", Especie_veget$info)
    Especie_veget$info<-sub("Floresta de Igapó", "11", Especie_veget$info)
    Especie_veget$info<-sub("Floresta de Terra Firme", "12", Especie_veget$info)
    Especie_veget$info<-sub("Floresta de Várzea", "13", Especie_veget$info)
    Especie_veget$info<-sub("Floresta Estacional Decidual", "14", Especie_veget$info)
    Especie_veget$info<-sub("Floresta Estacional Perenifólia", "15", Especie_veget$info)
    Especie_veget$info<-sub("Floresta Estacional Semidecidual", "16", Especie_veget$info)
    Especie_veget$info<-sub("Floresta Ombrófila \\(= Floresta Pluvial\\)", "17", Especie_veget$info)
    Especie_veget$info<-sub("Floresta Ombrófila Mista", "18", Especie_veget$info)
    Especie_veget$info<-sub("Manguezal", "19", Especie_veget$info)
    Especie_veget$info<-sub("Palmeiral", "20", Especie_veget$info)
    Especie_veget$info<-sub("Restinga", "21", Especie_veget$info)
    Especie_veget$info<-sub("Savana Amazônica", "22", Especie_veget$info)
    Especie_veget$info<-sub("Vegetação Aquática", "23", Especie_veget$info)
    Especie_veget$info<-sub("Vegetação Sobre Afloramentos Rochosos", "24", Especie_veget$info)
    Especie_veget$numero<-as.numeric(count(as.data.frame(strsplit(Especie_veget$info,"-"))))
    Especie_veget2<-data.frame(strsplit(Especie_veget$info,"-"))
    Especie_veget2<-as.data.frame(t(Especie_veget2))
    row.names(Especie_veget2)<-""
    Especie_veget<-cbind(Especie_veget,Especie_veget2)

    if(exists("Species")==T){
      sink(

        paste0(

          sub("Packages/CNCFloraR", "", getwd()),
          "/CNCFlora_data/outputs/AHK_scripts/fill_infobasic-", Species, ".ahk"

        )

      )
      cat("F4::\n")
      cat("\n")
      cat("run opera.exe -new http://cncflora.jbrj.gov.br/profiles/")
      cat(recorte)
      cat("/profile/profile:")
      cat(profile_sp)
      cat("/edit\n")
      cat("Sleep 3000\n")
      cat("Click, 180, 444\n")
      cat("Sleep 1000\n")
      cat("Send {Tab}\n")
      cat("Sleep 1000\n")
      cat("Send ^+{Home}\n")
      cat("Sleep 1000\n")
      cat("Send {Text}")
      cat(Especie_obra$info)
      cat("\n")
      cat("Sleep 1000\n")
      cat("Send {Tab}\n")
      cat("Sleep 1000\n")
      cat("Click, 180, 580\n")
      cat("Sleep 1000\n")
      cat("Send {Tab 2}\n")
      cat("Sleep 1000\n")
      cat("Send {Text}")
      cat(Especie_EOO$info)
      cat("\n")
      cat("Sleep 1000\n")
      cat("Send {Tab}\n")
      cat("Sleep 1000\n")
      cat("Send {Text}")
      cat(Especie_AOO$info)
      cat("\n")
      cat("Sleep 1000\n")
      cat("Send {Tab}\n")
      cat("Sleep 1000\n")
      cat("Send {Down ")
      cat(Especie_endemism$info)
      cat("}\n")
      cat("Sleep 1000\n")
      cat("Send {Tab}\n")
      cat("Send ^+{Home}\n")
      cat("Sleep 1000\n")
      cat("Send {Text}")
      cat(Especie_DistGeo$info)
      cat("\n")
      cat("Sleep 1000\n")
      cat("Send {Tab}\n")
      cat("Sleep 1000\n")
      cat("Click, 230, 581\n")
      cat("Sleep 1000\n")
      cat("Send {Tab}\n")
      cat("Sleep 1000\n")
      cat("Send {Enter}\n")
      cat("Sleep 1000\n")
      cat("Send {Text}")
      cat(Especie_Ref_FB2020$info)
      cat("\n")
      cat("Sleep 1000\n")
      cat("Send {Tab 3}\n")
      cat("Click, 180, 668\n")
      cat("Sleep 1000\n")
      cat("Send {End}\n")
      cat("Sleep 1000\n")
      cat("Click, 230, 172\n")
      cat("Sleep 1000\n")
      cat("Send {Tab}\n")
      cat("Sleep 1000\n")
      cat("Send {Enter}\n")
      cat("Sleep 1000\n")
      cat("Send +{Tab 2}\n")
      cat("Sleep 1000\n")
      if(Especie_lifeForm$numero==1){
        cat("Send {Down ")
        cat(Especie_lifeForm$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Click, 230, 261\n")
      }
      if(Especie_lifeForm$numero==2){
        cat("Send {Down ")
        cat(Especie_lifeForm$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_lifeForm$V2)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Click, 230, 290\n")
      }
      if(Especie_lifeForm$numero==3){
        cat("Send {Down ")
        cat(Especie_lifeForm$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_lifeForm$V2)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_lifeForm$V3)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Click, 230, 321\n")
      }
      if(Especie_lifeForm$numero==4){
        cat("Send {Down ")
        cat(Especie_lifeForm$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_lifeForm$V2)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_lifeForm$V3)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_lifeForm$V4)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Click, 230, 350\n")
      }
      cat("Send {Tab}\n")
      cat("Sleep 1000\n")
      cat("Send {Enter}\n")
      cat("Send +{Tab 2}\n")
      cat("Sleep 1000\n")
      if(Especie_habit$numero==1){
        cat("Send {Down ")
        cat(Especie_habit$V1)
        cat("}\n")
        cat("Sleep 1000\n")
      }
      if(Especie_habit$numero==2){
        cat("Send {Down ")
        cat(Especie_habit$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_habit$V2)
        cat("}\n")
        cat("Sleep 1000\n")
      }
      cat("Send {Tab}\n")
      cat("Sleep 1000\n")
      cat("Send {End}\n")
      cat("Sleep 1000\n")
      cat("Click, 230, 391\n")
      cat("Sleep 1000\n")
      cat("Send {Tab}\n")
      cat("Sleep 1000\n")
      cat("Send {Enter}\n")
      cat("Sleep 1000\n")
      cat("Send +{Tab 2}\n")
      cat("Sleep 1000\n")
      if(Especie_bioma$numero==1){
        cat("Send {Down ")
        cat(Especie_bioma$V1)
        cat("}\n")
      }
      if(Especie_bioma$numero==2){
        cat("Send {Down ")
        cat(Especie_bioma$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_bioma$V2)
        cat("}\n")
      }
      if(Especie_bioma$numero==3){
        cat("Send {Down ")
        cat(Especie_bioma$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_bioma$V2)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_bioma$V3)
        cat("}\n")
      }
      if(Especie_bioma$numero==4){
        cat("Send {Down ")
        cat(Especie_bioma$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_bioma$V2)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_bioma$V3)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_bioma$V4)
        cat("}\n")
      }
      if(Especie_bioma$numero==5){
        cat("Send {Down ")
        cat(Especie_bioma$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_bioma$V2)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_bioma$V3)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_bioma$V4)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_bioma$V5)
        cat("}\n")
      }
      if(Especie_bioma$numero==6){
        cat("Send {Down ")
        cat(Especie_bioma$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_bioma$V2)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_bioma$V3)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_bioma$V4)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_bioma$V5)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_bioma$V6)
        cat("}\n")
      }
      cat("Sleep 1000\n")
      cat("Send ^{End}\n")
      cat("Sleep 1000\n")
      cat("Click, 230, 452\n")
      cat("Sleep 1000\n")
      cat("Send {Tab}\n")
      cat("Sleep 1000\n")
      cat("Send {Enter}\n")
      cat("Sleep 1000\n")
      cat("Send +{Tab 2}\n")
      cat("Sleep 1000\n")
      if(Especie_veget$numero==1){
        cat("Send {Down ")
        cat(Especie_veget$V1)
        cat("}\n")
        cat("Sleep 1000\n")
      }
      if(Especie_veget$numero==2){
        cat("Send {Down ")
        cat(Especie_veget$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V2)
        cat("}\n")
        cat("Sleep 1000\n")
      }
      if(Especie_veget$numero==3){
        cat("Send {Down ")
        cat(Especie_veget$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V2)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V3)
        cat("}\n")
        cat("Sleep 1000\n")
      }
      if(Especie_veget$numero==4){
        cat("Send {Down ")
        cat(Especie_veget$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V2)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V3)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V4)
        cat("}\n")
        cat("Sleep 1000\n")
      }
      if(Especie_veget$numero==5){
        cat("Send {Down ")
        cat(Especie_veget$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V2)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V3)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V4)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V5)
        cat("}\n")
        cat("Sleep 1000\n")
      }
      if(Especie_veget$numero==6){
        cat("Send {Down ")
        cat(Especie_veget$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V2)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V3)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V4)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V5)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V6)
        cat("}\n")
        cat("Sleep 1000\n")
      }
      if(Especie_veget$numero==7){
        cat("Send {Down ")
        cat(Especie_veget$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V2)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V3)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V4)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V5)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V6)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V7)
        cat("}\n")
        cat("Sleep 1000\n")
      }
      if(Especie_veget$numero==8){
        cat("Send {Down ")
        cat(Especie_veget$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V2)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V3)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V4)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V5)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V6)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V7)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V8)
        cat("}\n")
        cat("Sleep 1000\n")
      }
      if(Especie_veget$numero==9){
        cat("Send {Down ")
        cat(Especie_veget$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V2)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V3)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V4)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V5)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V6)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V7)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V8)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V9)
        cat("}\n")
        cat("Sleep 1000\n")
      }
      if(Especie_veget$numero==10){
        cat("Send {Down ")
        cat(Especie_veget$V1)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V2)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V3)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V4)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V5)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V6)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V7)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V8)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V9)
        cat("}\n")
        cat("Sleep 1000\n")
        cat("Send {Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Enter}\n")
        cat("Sleep 1000\n")
        cat("Send +{Tab 2}\n")
        cat("Sleep 1000\n")
        cat("Send {Down ")
        cat(Especie_veget$V10)
        cat("}\n")
        cat("Sleep 1000\n")
      }
      cat("Send {Tab 4}\n")
      cat("Sleep 1000\n")
      cat("Send {Enter}\n")
      cat("Sleep 10000\n")
      cat("Send ^w\n")
      cat("return\n")
      sink()

    }

  }


  #Renderizando o output final (All)

  sink(

    paste0(

      sub("Packages/CNCFloraR", "", getwd()),
      "/CNCFlora_data/outputs/AHK_scripts/fill_infobasic.ahk"

    )

  )
  cat("F4::")
  cat("\n")

  for(i in listOfSpecies$species){

    Script <- readtext(

      paste0(

        sub("Packages/CNCFloraR", "", getwd()),
        "/CNCFlora_data/outputs/AHK_scripts/fill_infobasic-", i, ".ahk"

      )

    )
    Script$text<-sub("return","Sleep 5000\n",Script$text)
    Script$text<-sub("F4\\:\\:","",Script$text)

    cat(Script$text)
    cat("\n")

    file.remove(

      paste0(

        sub("Packages/CNCFloraR", "", getwd()),
        "/CNCFlora_data/outputs/AHK_scripts/fill_infobasic-", i, ".ahk"

      )

    )

  }

  cat("\nreturn")
  sink()

  answer <- ""

  while(answer != "Y" |
        answer != "N" ){

    answer <-
      toupper(readline("Open the file path? (y/n)"))

    if(answer == "Y"){

      suppressWarnings(
        shell(

          paste0(

            "explorer.exe ",
            gsub(

              "/", "\\\\",

              paste0(

                sub(

                  "Packages/CNCFloraR",
                  "",
                  getwd()

                ),
                "/CNCFlora_data/outputs/AHK_scripts"

              )

            )

          ),
          intern = TRUE

        )

      )

      break

    }

    if(answer == "N"){

      break

    }

  }

}
