fixUCsNames <- function(shapefile){

  UCs_shape <- shapefile

  UCs_shape$NOME_UC1 <- str_to_title(UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\sE\\s", " e ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\sDe\\s", " de ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\sDo\\s", " do ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\sDa\\s", " da ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\sDas\\s", " das ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\sDos\\s", " dos ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\s\\s", " ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\s\\s", " ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Àrea\\s", "Área ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Area\\s", "Área ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("daÁrea\\s", "da Área ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Ecologica", "Ecológica", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Estacao", "Estação", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\sIii", " III", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\sIi", " II", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\sIv", " IV", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\sVii", " VII", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub('""', '"', UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\s-\\sRvs\\sPalmares", "", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Ciriáco", "Ciriaco", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Municípal", "Municipal", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Caetétaperaçu", "Caeté-Taperaçu", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Iguatemí", "Iguatemi", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Rppn\\s", "Reserva Particular do Patrimônio Natural ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Arie\\s", "Área de Relevante Interesse Ecológico ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Arie\\s", "Área de Relevante Interesse Ecológico ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("(\\s|^)Apa\\s", "Área de Proteção Ambiental ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Ecológico-\\sIlhas", "Ecológico - Ilhas", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Metrolpolitana", "Metropolitana", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Tamandare", "Tamandaré", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Refugio", "Refúgio", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Palacio", "Palácio", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Antonio", "Antônio", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Piraque", "Piraquê", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Bugiu", "Bugio", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Iguaçú", "Iguaçu", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Zabele", "Zabelê", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Muncipal", "Municipal", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Chapadao", "Chapadão", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Araucarias", "Araucárias", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Cabreuva", "Cabreúva", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Munumento", "Monumento", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Arquipelago", "Arquipélago", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\sAndre\\s", " André ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Patriomônio", "Patrimônio", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Paraiba", "Paraíba", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Caparao", "Caparaó", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\sCapao\\s", " Capão ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Corrego", "Córrego", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Chaua", "Chauá", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Parnaiba", "Parnaíba", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Pracuuba", "Pracuúba", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Biologica", "Biológica", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Sassafras", "Sassafrás", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Lençois", "Lençóis", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Aguas\\s", "Águas ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Patrimonio", "Patrimônio", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\sOrgãos", " Órgãos", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\sPerimetro\\s", " Perímetro ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\sTejupa\\s", " Tejupá ", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Área\\sde\\sProteção\\sAmbiental\\s-Área\\sde\\sProteção\\sAmbiental\\sda\\sPerdição", "Área de Proteção Ambiental da Perdição", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Ambiental\\sCorumbataí\\sBotucatu\\sTejupá\\sPerímetro", "Ambiental Corumbataí, Botucatu e Tejupá - Perímetro", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Alegre\\s1a", "Alegre 1A", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Cb\\s-\\sCartonagem", "CB - Cartonagem", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\sApaep", "", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\s\\/", "/", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\/\\s", "/", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("D(´|')água", "d'Água", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Dágua", "d'Água", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Caixa\\sD\\sÁgua", "Caixa d'Água", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("D(´|')Ouro", "d'Ouro", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\.", "", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Botujuru-Serra", "Botujuru - Serra", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("Sustentavel", "Sustentável", UCs_shape$NOME_UC1)
  UCs_shape$NOME_UC1 <- gsub("\\s\\(Sc\\)", "", UCs_shape$NOME_UC1)

  return(UCs_shape)

}
